### ISSUE TITLE
npm start with error because package too old

### ISSUE THREAD

**Issue by liuzhenyulive** [aspnetboilerplate/eventcloud#34]
This project seems to have been no longer a long time, and Angular's package dependencies are also very old. When running npm, various errors, consider whether to update the angular package?

**Comment by alirizaadiyahsi** [comment]
What errors are you getting?

**Comment by liuzhenyulive** [comment]
After run npm start,I get following error .

```
λ npm start

> EventCloud@0.0.0 start C:\MyBox\Github\eventcloud\aspnet-core-angular\angular
> ng serve --host 0.0.0.0 --port 4200

** NG Live Development Server is listening on 0.0.0.0:4200, open your browser on http://localhost:4200/ **
Date: 2019-04-02T12:52:35.465Z
Hash: fe8de2f80044ac7d8231
Time: 8850ms
chunk {inline} inline.bundle.js (inline) 3.85 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 2.91 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 577 bytes [initial] [rendered]
chunk {scripts} scripts.bundle.js (scripts) 1.79 MB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 1.67 MB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 867 kB [initial] [rendered]

ERROR in node_modules/@types/jasmine/index.d.ts(142,47): error TS1005: ';' expected.
node_modules/@types/jasmine/index.d.ts(142,90): error TS1005: '(' expected.
node_modules/@types/jasmine/index.d.ts(142,104): error TS1005: ']' expected.
node_modules/@types/jasmine/index.d.ts(142,112): error TS1005: ',' expected.
node_modules/@types/jasmine/index.d.ts(142,113): error TS1136: Property assignment expected.
node_modules/@types/jasmine/index.d.ts(142,121): error TS1005: ')' expected.
node_modules/@types/jasmine/index.d.ts(142,147): error TS1005: '(' expected.
node_modules/@types/jasmine/index.d.ts(142,162): error TS1005: ']' expected.
node_modules/@types/jasmine/index.d.ts(142,163): error TS1005: ',' expected.
node_modules/@types/jasmine/index.d.ts(142,164): error TS1136: Property assignment expected.
node_modules/@types/jasmine/index.d.ts(142,165): error TS1136: Property assignment expected.
node_modules/@types/jasmine/index.d.ts(142,179): error TS1005: ',' expected.
node_modules/@types/jasmine/index.d.ts(142,183): error TS1005: ':' expected.
node_modules/@types/jasmine/index.d.ts(142,208): error TS1005: '{' expected.
node_modules/@types/jasmine/index.d.ts(142,217): error TS1005: ':' expected.
node_modules/@types/jasmine/index.d.ts(142,222): error TS1005: ',' expected.
node_modules/@types/jasmine/index.d.ts(142,227): error TS1005: ':' expected.
node_modules/@types/jasmine/index.d.ts(142,228): error TS1109: Expression expected.
node_modules/@types/jasmine/index.d.ts(142,230): error TS1005: ')' expected.
node_modules/@types/jasmine/index.d.ts(635,30): error TS1005: ';' expected.
node_modules/@types/jasmine/index.d.ts(720,1): error TS1128: Declaration or statement expected.


webpack: Failed to compile.
```

I found some solutions on the Internet saying to update the version of typescript,so ,i update the typescript version to  `"typescript": "^2.8.9"`,But still get new error.

```
> EventCloud@0.0.0 start C:\MyBox\Github\eventcloud\aspnet-core-angular\angular
> ng serve --host 0.0.0.0 --port 4200


@angular/compiler-cli@5.2.11 requires typescript@'>=2.4.2 <2.7.0' but 2.9.2 was found instead.
Using this version can result in undefined behaviour and difficult to debug problems.

Please run the following command to install a compatible version of TypeScript.

    npm install typescript@'>=2.4.2 <2.7.0'

To disable this warning run "ng set warnings.typescriptMismatch=false".

** NG Live Development Server is listening on 0.0.0.0:4200, open your browser on http://localhost:4200/ **
Date: 2019-04-02T12:59:33.839Z
Hash: 1b21ac9a22f48468c9c6
Time: 15909ms
chunk {inline} inline.bundle.js (inline) 3.85 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 2.91 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 577 bytes [initial] [rendered]
chunk {scripts} scripts.bundle.js (scripts) 1.79 MB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 1.67 MB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 867 kB [initial] [rendered]

ERROR in src/shared/helpers/SignalRAspNetCoreHelper.ts(9,9): error TS2322: Type '{ autoConnect: true; connect: undefined; hubs: undefined; qs: string; url: string; }' is not assignable to type 'typeof signalr'.
  Property 'startConnection' is missing in type '{ autoConnect: true; connect: undefined; hubs: undefined; qs: string; url: string; }'.


webpack: Failed to compile.

```

**Comment by liuzhenyulive** [comment]
I try to solve the error by the solution
[https://github.com/aspnetboilerplate/module-zero-core-template/issues/207](url)
but it sill not work.
with new error.
```
ERROR in ./node_modules/abp-ng2-module/src/abp-user-configuration.service.ts
Module build failed: Error: C:\MyBox\Github\eventcloud\aspnet-core-angular\angular\node_modules\abp-ng2-module\src\abp-user-configuration.service.ts is missing from the TypeScript compilation. Please make sure it is in
your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\MyBox\Github\eventcloud\aspnet-core-angular\angular\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (C:\MyBox\Github\eventcloud\aspnet-core-angular\angular\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:68:7)
ERROR in ./node_modules/abp-ng2-module/src/abpHttp.ts
Module build failed: Error: C:\MyBox\Github\eventcloud\aspnet-core-angular\angular\node_modules\abp-ng2-module\src\abpHttp.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\MyBox\Github\eventcloud\aspnet-core-angular\angular\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (C:\MyBox\Github\eventcloud\aspnet-core-angular\angular\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:68:7)

webpack: Failed to compile.
```
I guess the package is too old, need to update the whole, just guess, I am a .net backstage developer, not good at angular, but I still want to run to see the results.

Best Regards!

**Comment by ismcagdas** [comment]
@liuzhenyulive we are updating the solution, it will be available soon.

**Comment by liuzhenyulive** [comment]
Thank you, I will continue to pay attention.

**Comment by rohitPagal** [comment]
yes guys....please update the solution asap for the love of dog

**Comment by alirizaadiyahsi** [comment]
https://github.com/aspnetboilerplate/eventcloud/pull/35

**Comment by liuzhenyulive** [comment]
@alirizaadiyahsi 
Thank for you update so quick, but why after update I can't find the event menu?
![Snipaste_2019-04-11_21-43-27](https://user-images.githubusercontent.com/23184470/55962365-48a97300-5ca3-11e9-8f39-af8c13b3057e.png)

**Comment by liuzhenyulive** [comment]
And this is the latest version

**Comment by liuzhenyulive** [comment]
I found the reason, we need to switch to Default Tenantid, can't be empty Tenantid
![Snipaste_2019-04-11_22-39-58](https://user-images.githubusercontent.com/23184470/55966382-dccb0880-5caa-11e9-8c19-46dc836524b8.png)
